from .labels import NUM_CLASSES as labels_NUM_CLASSES

BB_CNN_FILTERS = 2
NUM_CNNS = 10
BB_SIZE = (105, 50)

VALID_YOLO_LABELS = {"person",}
NUM_CLASSES = labels_NUM_CLASSES

CLIP_SIZE = 25
THREED_CNN_FILTERS = 16
THREED_CNN_KERNEL_SIZE = (3, 3, 3)
THREED_CNN_INPUT_SHAPE = (25, 224, 224, 3)
THREED_CNN_POOL_SIZE = (1, 2, 2)
THREED_CNN_POOL_STRIDES = (1, 2, 2)
