from .labels import NUM_CLASSES as labels_NUM_CLASSES

BATCH_SIZE = 32
EPOCHS = 2

BB_CNN_FILTERS = 2
NUM_CNNS = 10
BB_SIZE = (105, 50)

VALID_YOLO_LABELS = {"person",}
NUM_CLASSES = labels_NUM_CLASSES

CLIP_SIZE = 25
THREED_CNN_FILTERS = 2
THREED_CNN_KERNEL_SIZE = (5, 5, 5)
THREED_CNN_INPUT_SHAPE = (25, 255, 255, 3)
THREED_CNN_POOL_SIZE = (1, 2, 2)
THREED_CNN_POOL_STRIDES = (1, 2, 2)
